#![cfg(any(feature = "coordinator-assisted", feature = "hazmat-real-mldsa"))]

use lattice_aggregation::{
    production::provider::{StandardMldsa65Provider, UnavailableMldsa65Provider},
    ThresholdError, ThresholdPublicKey, ThresholdSignature,
};

#[test]
fn unavailable_provider_fails_closed() {
    let public_key = ThresholdPublicKey([0; 1952]);
    let signature = ThresholdSignature([0; 3309]);
    let err = UnavailableMldsa65Provider::verify(&public_key, b"msg", &signature).unwrap_err();
    assert_eq!(
        err,
        ThresholdError::BackendUnavailable {
            reason: "standard ML-DSA provider is not enabled",
        }
    );
}

#[cfg(feature = "hazmat-real-mldsa")]
#[test]
fn hazmat_provider_verifies_mldsa65_signature_from_fixed_seed() {
    use lattice_aggregation::production::provider::HazmatMldsa65Provider;
    use ml_dsa::{Keypair, MlDsa65, SignatureEncoding, Signer, SigningKey};

    let seed = [0x42; 32].into();
    let signing_key = SigningKey::<MlDsa65>::from_seed(&seed);
    let message = b"lattice-aggregation hazmat ML-DSA-65 provider smoke";
    let public_key = threshold_public_key_from(&signing_key.verifying_key().encode());
    let signature = threshold_signature_from(&signing_key.sign(message).to_bytes());

    assert!(
        HazmatMldsa65Provider::verify(&public_key, message, &signature).unwrap(),
        "hazmat provider should accept a standard ML-DSA-65 signature generated by the optional provider"
    );
}

#[cfg(feature = "hazmat-real-mldsa")]
#[test]
fn hazmat_provider_rejects_mutated_message_and_signature() {
    use lattice_aggregation::production::provider::HazmatMldsa65Provider;
    use ml_dsa::{Keypair, MlDsa65, SignatureEncoding, Signer, SigningKey};

    let seed = [0x24; 32].into();
    let signing_key = SigningKey::<MlDsa65>::from_seed(&seed);
    let message = b"lattice-aggregation hazmat ML-DSA-65 rejection smoke";
    let public_key = threshold_public_key_from(&signing_key.verifying_key().encode());
    let mut signature = threshold_signature_from(&signing_key.sign(message).to_bytes());

    assert!(
        !HazmatMldsa65Provider::verify(&public_key, b"mutated message", &signature).unwrap(),
        "hazmat provider should reject a valid signature over a different message"
    );

    signature.0[0] ^= 0x01;
    assert!(
        !HazmatMldsa65Provider::verify(&public_key, message, &signature).unwrap(),
        "hazmat provider should reject mutated signature bytes"
    );
}

#[cfg(feature = "hazmat-real-mldsa")]
#[test]
#[ignore = "requires checked-in ACVP/FIPS ML-DSA-65 vectors"]
fn hazmat_provider_verifies_mldsa65_kats() {
    panic!("ACVP/FIPS ML-DSA-65 vectors must be checked in before production promotion");
}

#[cfg(feature = "hazmat-real-mldsa")]
fn threshold_public_key_from(encoded: &[u8]) -> ThresholdPublicKey {
    let mut bytes = [0u8; 1952];
    bytes.copy_from_slice(encoded);
    ThresholdPublicKey(bytes)
}

#[cfg(feature = "hazmat-real-mldsa")]
fn threshold_signature_from(encoded: &[u8]) -> ThresholdSignature {
    let mut bytes = [0u8; 3309];
    bytes.copy_from_slice(encoded);
    ThresholdSignature(bytes)
}
