#![cfg(any(feature = "coordinator-assisted", feature = "raw-real-mldsa"))]

use lattice_aggregation::{
    production::provider::{StandardMldsa65Provider, UnavailableMldsa65Provider},
    ThresholdError, ThresholdPublicKey, ThresholdSignature,
};

#[test]
fn unavailable_provider_fails_closed() {
    let public_key = ThresholdPublicKey([0; 1952]);
    let signature = ThresholdSignature([0; 3309]);
    let err = UnavailableMldsa65Provider::verify(&public_key, b"msg", &signature).unwrap_err();
    assert_eq!(
        err,
        ThresholdError::BackendUnavailable {
            reason: "standard ML-DSA provider is not enabled",
        }
    );
}

#[cfg(feature = "raw-real-mldsa")]
#[test]
fn hazmat_provider_verifies_mldsa65_signature_from_fixed_seed() {
    use lattice_aggregation::production::provider::HazmatMldsa65Provider;
    use ml_dsa::{Keypair, MlDsa65, SignatureEncoding, Signer, SigningKey};

    let seed = [0x42; 32].into();
    let signing_key = SigningKey::<MlDsa65>::from_seed(&seed);
    let message = b"lattice-aggregation hazmat ML-DSA-65 provider smoke";
    let public_key = threshold_public_key_from(&signing_key.verifying_key().encode());
    let signature = threshold_signature_from(&signing_key.sign(message).to_bytes());

    assert!(
        HazmatMldsa65Provider::verify(&public_key, message, &signature).unwrap(),
        "hazmat provider should accept a standard ML-DSA-65 signature generated by the optional provider"
    );
}

#[cfg(feature = "raw-real-mldsa")]
#[test]
fn hazmat_provider_rejects_mutated_message_and_signature() {
    use lattice_aggregation::production::provider::HazmatMldsa65Provider;
    use ml_dsa::{Keypair, MlDsa65, SignatureEncoding, Signer, SigningKey};

    let seed = [0x24; 32].into();
    let signing_key = SigningKey::<MlDsa65>::from_seed(&seed);
    let message = b"lattice-aggregation hazmat ML-DSA-65 rejection smoke";
    let public_key = threshold_public_key_from(&signing_key.verifying_key().encode());
    let mut signature = threshold_signature_from(&signing_key.sign(message).to_bytes());

    assert!(
        !HazmatMldsa65Provider::verify(&public_key, b"mutated message", &signature).unwrap(),
        "hazmat provider should reject a valid signature over a different message"
    );

    signature.0[0] ^= 0x01;
    assert!(
        !HazmatMldsa65Provider::verify(&public_key, message, &signature).unwrap(),
        "hazmat provider should reject mutated signature bytes"
    );
}

#[cfg(feature = "raw-real-mldsa")]
#[test]
fn hazmat_provider_verifies_mldsa65_kats() {
    use lattice_aggregation::production::provider::HazmatMldsa65Provider;
    use serde::Deserialize;

    #[derive(Deserialize)]
    struct Fixture {
        name: String,
        source_commit: String,
        parameter_set: String,
        mode: String,
        revision: String,
        signature_interface: String,
        external_mu: Option<bool>,
        pre_hash: String,
        source_prompt_sha256: String,
        source_expected_results_sha256: String,
        tests: Vec<KatCase>,
    }

    #[derive(Deserialize)]
    struct KatCase {
        #[serde(rename = "tcId")]
        tc_id: u32,
        #[serde(rename = "testPassed")]
        test_passed: bool,
        message_hex: String,
        context_hex: String,
        public_key_hex: String,
        signature_hex: String,
    }

    let fixture: Fixture = serde_json::from_str(include_str!(
        "fixtures/acvp_mldsa65_sigver_fips204_sample.json"
    ))
    .expect("ACVP ML-DSA-65 fixture should parse");

    assert_eq!(
        fixture.name,
        "nist-acvp-server-mldsa65-sigver-fips204-sample"
    );
    assert_eq!(
        fixture.source_commit,
        "15c0f3deeefbfa8cb6cd32a99e1ca3b738c66bf0"
    );
    assert_eq!(fixture.parameter_set, "ML-DSA-65");
    assert_eq!(fixture.mode, "sigVer");
    assert_eq!(fixture.revision, "FIPS204");
    assert_eq!(fixture.signature_interface, "external");
    assert_eq!(fixture.external_mu, None);
    assert_eq!(fixture.pre_hash, "pure");
    assert_eq!(
        fixture.source_prompt_sha256,
        "2a9b7fcbefdd8e69dd6fbe6b4abb7130d855e8429aaa6f4904385e68b7e63d3a"
    );
    assert_eq!(
        fixture.source_expected_results_sha256,
        "33e0ea7dd9c3b0206712da50286ad746864371433977225ab77e8aae76358842"
    );
    assert!(
        fixture.tests.iter().any(|case| case.test_passed),
        "fixture must include at least one accepting ACVP sample"
    );
    assert!(
        fixture.tests.iter().any(|case| !case.test_passed),
        "fixture must include at least one rejecting ACVP sample"
    );

    for case in fixture.tests {
        let message = decode_hex(&case.message_hex);
        let context = decode_hex(&case.context_hex);
        let public_key = threshold_public_key_from(&decode_hex(&case.public_key_hex));
        let signature = threshold_signature_from(&decode_hex(&case.signature_hex));
        let accepted =
            HazmatMldsa65Provider::verify_with_context(&public_key, &message, &context, &signature)
                .expect("hazmat provider should not error on ACVP sample vector");

        assert_eq!(
            accepted, case.test_passed,
            "ACVP ML-DSA-65 sigVer tcId {} did not match expected result",
            case.tc_id
        );
    }
}

#[cfg(feature = "raw-real-mldsa")]
fn threshold_public_key_from(encoded: &[u8]) -> ThresholdPublicKey {
    let mut bytes = [0u8; 1952];
    bytes.copy_from_slice(encoded);
    ThresholdPublicKey(bytes)
}

#[cfg(feature = "raw-real-mldsa")]
fn threshold_signature_from(encoded: &[u8]) -> ThresholdSignature {
    let mut bytes = [0u8; 3309];
    bytes.copy_from_slice(encoded);
    ThresholdSignature(bytes)
}

#[cfg(feature = "raw-real-mldsa")]
fn decode_hex(hex: &str) -> Vec<u8> {
    assert!(
        hex.len().is_multiple_of(2),
        "hex string should contain an even number of characters"
    );

    hex.as_bytes()
        .chunks_exact(2)
        .map(|pair| {
            let high = hex_nibble(pair[0]);
            let low = hex_nibble(pair[1]);
            (high << 4) | low
        })
        .collect()
}

#[cfg(feature = "raw-real-mldsa")]
fn hex_nibble(byte: u8) -> u8 {
    match byte {
        b'0'..=b'9' => byte - b'0',
        b'a'..=b'f' => byte - b'a' + 10,
        b'A'..=b'F' => byte - b'A' + 10,
        _ => panic!("invalid hex byte: {byte}"),
    }
}
